# SPDX-License-Identifier: GPL-2.0-or-later

# Tests requiring external assets not yet available in CI are commented out.
test_hexagon_timeouts = {
  'arch_tests': 180,
  'linux': 480,
  'minivm': 180,
  'qurt': 2400,
  'sdk': 300,
  'systests': 480,
  'sa8775p_cdsp0': 180,
}

tests_hexagon_system_thorough = [
  'arch_tests',
  'linux',
  'minivm',
  'qurt',
  'sdk',
  'systests',
  'sa8775p_cdsp0',
]

