# SPDX-License-Identifier: GPL-2.0-or-later

test_hexagon_timeouts = {
  'sival': 240,
  'qurt': 2400,
  'minivm': 180,
  'linux': 180,
  'systests': 180,
  'sdk': 180,
  'sa8775p_cdsp0': 180,
  'sc8480xp_cdsp0': 180,
}

tests_hexagon_system_thorough = [
  'minivm',
  'linux',
  'sival',
  'qurt',
  'virtio',
  'systests',
  'sdk',
  'sa8775p_cdsp0',
  'sc8480xp_cdsp0',
]
