# SPDX-License-Identifier: GPL-2.0-or-later

test_hexagon_timeouts = {
  'hexagon_sival': 240,
  'hexagon_qurt': 2400,
  'hexagon_minivm': 180,
  'hexagon_linux': 180,
}

tests_hexagon_system_thorough = [
  'hexagon_minivm',
  'hexagon_linux',
  'hexagon_sival',
  'hexagon_qurt',
  'hexagon_virtio',
]
