image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u22:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      auto_cancel:
        on_job_failure: all
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

variables:
  FF_SCRIPT_SECTIONS: True
  GIT_DEPTH: 1

  QUIC_BUILD_DIR: build
  QUIC_BUILD_DIR_ABS: "${CI_PROJECT_DIR}/${QUIC_BUILD_DIR}"

checkpatch:
  stage: .pre
  variables:
    GIT_DEPTH: 250
    GIT_FETCH_EXTRA_FLAGS: --filter=blob:none --filter=tree:0 --prune --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script: quic-gitlab-ci.d/checkpatch.sh
  timeout: 5 minutes
  allow_failure: true

user_guide:
  stage: build
  script:
    - make -C quic/user_guide/ html latexpdf
  artifacts:
    paths: [ quic/user_guide/_build/html, quic/user_guide/_build/latex ]
    expire_in: 1 days

.test-artifacts:
  artifacts:
    when: on_failure
    paths:
      - ${QUIC_BUILD_DIR_ABS}
    expire_in: 4 days

.build-job:
  stage: build
  script: ./quic-gitlab-ci.d/build.sh
  variables:
    QUIC_BUILD_LOG: ${QUIC_BUILD_DIR_ABS}/build.log
    QUIC_COPROC_REF: qemu-coproc-plugin-13.0.0
  artifacts:
    when: always
    paths:
      - ${QUIC_BUILD_DIR_ABS}
    expire_in: 1 day

# QEMU Hexagon for Linux on x86_64
qemu-hexagon-linux-x86_64:
  extends: .build-job
  variables:
    QUIC_BUILD_CONFIG: hexagon
    QUIC_COPROC_JOB: linux-x86_64-tag

# Keep the nightly builds for a little longer, just in case
qemu-hexagon-linux-x86_64-schedule:
  extends: qemu-hexagon-linux-x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    expire_in: 3 days

qemu-hexagon-linux-x86_64-tag:
  extends: qemu-hexagon-linux-x86_64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

qemu-hexagon-linux-x86_64-check-tcg:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-check-tcg.sh

qemu-hexagon-linux-x86_64-check-tcg-mttcg:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-check-tcg.sh -m

qemu-hexagon-linux-x86_64-check:
  stage: test
  extends: .test-artifacts
  tags: [ new-libseccomp ]
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose

qemu-hexagon-linux-x86_64-qurt:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-functional-test.sh func-hexagon-qurt

qemu-hexagon-linux-x86_64-sival:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-functional-test.sh func-hexagon-sival

qemu-hexagon-linux-x86_64-boot:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-functional-test.sh func-hexagon-linux

qemu-hexagon-linux-x86_64-virtio:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: ./quic/run-functional-test.sh func-hexagon-virtio

qemu-hexagon-linux-x86_64-misc:
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64" ]
  script: >
    ./quic/run-functional-test.sh func-hexagon-sdk &&
    ./quic/run-functional-test.sh func-hexagon-minivm &&
    ./quic/run-functional-test.sh func-hexagon-systests &&
    ./quic/run-functional-test.sh func-hexagon-sa8775p_cdsp0

qemu-hexagon-linux-x86_64-perf:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  needs: [ "qemu-hexagon-linux-x86_64" ]
  tags:
    - performance-hardware
  script: ./quic-gitlab-ci.d/hexagon-linux-x86_64-perf.sh
  artifacts:
    when: always
    paths: [ "perf-results.json" ]
    reports:
      metrics: metrics.txt
    expire_in: 4 days

qemu-hexagon-linux-x86_64-perf-mttcg:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  needs: [ "qemu-hexagon-linux-x86_64" ]
  tags:
    - performance-hardware
  script: ./quic-gitlab-ci.d/hexagon-linux-x86_64-perf-mttcg.sh
  artifacts:
    when: always
    paths: [ "perf-results.json" ]
    reports:
      metrics: metrics.txt
    expire_in: 4 days

qemu-hexagon-linux-x86_64-perf-ml:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  needs: [ "qemu-hexagon-linux-x86_64" ]
  tags:
    - performance-hardware
  script: ./quic-gitlab-ci.d/hexagon-linux-x86_64-perf-ml.sh
  artifacts:
    when: always
    paths: [ "perf-results.json" ]
    reports:
      metrics: metrics.txt
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

fetch-iset:
  tags:
    - publish_runner # We need a node with access to the NFS paths for iset
  stage: test
  script:
    - cp /prj/qct/coredev/hexagon/sitelinks/arch/pkg/arch/x86_64/v73_stable/src/arch/iset.py ./
  artifacts:
    paths: [ "iset.py" ]

qemu-hexagon-linux-x86_64-packet-verif:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  needs: [ "qemu-hexagon-linux-x86_64", "fetch-iset" ]
  script: ./quic-gitlab-ci.d/packet-verif.sh
  artifacts:
    when: on_failure
    paths: [ "verif-qemu-hexagon",  ]
    expire_in: 7 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

# QEMU Hexagon for Linux on x86_64 with sanatizers enabled
qemu-hexagon-linux-x86_64-san:
  extends: .build-job
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  variables:
    QUIC_BUILD_CONFIG: hexagon-san
    QUIC_COPROC_JOB: linux-x86_64-tag

qemu-hexagon-linux-x86_64-san-check-tcg:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64-san" ]
  script: ./quic/run-check-tcg.sh

qemu-hexagon-linux-x86_64-san-check:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  extends: .test-artifacts
  tags: [ new-libseccomp ]
  needs: [ "qemu-hexagon-linux-x86_64-san" ]
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose

qemu-hexagon-linux-x86_64-san-sival:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64-san" ]
  script: ./quic/run-functional-test.sh func-hexagon-sival

qemu-hexagon-linux-x86_64-san-boot:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64-san" ]
  script: ./quic/run-functional-test.sh func-hexagon-linux
  when: manual
  allow_failure: true

qemu-hexagon-linux-x86_64-san-virtio:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  extends: .test-artifacts
  needs: [ "qemu-hexagon-linux-x86_64-san" ]
  script: ./quic/run-functional-test.sh func-hexagon-virtio

# QEMU Hexagon for macOS
qemu-hexagon-macOS:
  extends: .build-job
  variables:
    QUIC_BUILD_CONFIG: hexagon-mac
    QUIC_COPROC_JOB: mac-tag
  tags:
    - mac

qemu-hexagon-macOS-tag:
  extends: qemu-hexagon-macOS
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

# QEMU Hexagon for Linux on x86_64 without idef parser
qemu-hexagon-linux-x86_64-no-idef-parser:
  extends: .build-job
  variables:
    QUIC_BUILD_CONFIG: hexagon-no-idef-parser
    QUIC_COPROC_JOB: linux-x86_64-tag
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

qemu-hexagon-linux-x86_64-no-idef-parser-check-tcg:
  stage: test
  extends: .test-artifacts
  dependencies:
    - qemu-hexagon-linux-x86_64-no-idef-parser
  script: ./quic/run-check-tcg.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

qemu-hexagon-linux-x86_64-no-idef-parser-check:
  stage: test
  extends: .test-artifacts
  tags: [ new-libseccomp ]
  dependencies:
    - qemu-hexagon-linux-x86_64-no-idef-parser
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

# QEMU Hexagon for Windows on x86_64
qemu-hexagon-windows-x86_64:
  extends: .build-job
  image: docker-registry.qualcomm.com/qqvp/qemu:windows-x86_64-cross
  variables:
    QUIC_BUILD_CONFIG: hexagon-minimal-cross
    QUIC_COPROC_JOB: windows-x86_64-tag

qemu-hexagon-windows-x86_64-tag:
  extends: qemu-hexagon-windows-x86_64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

qemu-hexagon-windows-x86_64-perf-ml:
  image: docker-registry.qualcomm.com/qqvp/qemu:windows-x86_64-test
  stage: test
  needs: [ "qemu-hexagon-windows-x86_64" ]
  tags:
    - windows
    - x86_64
  timeout: 3h
  script: ./quic/msys2-ucrt64.ps1 ./quic-gitlab-ci.d/hexagon-windows-x86_64-perf-ml.sh
  artifacts:
    when: always
    paths: [ "perf-results.json" ]
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

# QEMU Hexagon for Linux on aarch64
qemu-hexagon-linux-aarch64:
  extends: .build-job
  image: docker-registry.qualcomm.com/qqvp/qemu:linux-aarch64-cross
  variables:
    QUIC_BUILD_CONFIG: hexagon-linux-aarch64-cross

qemu-hexagon-linux-aarch64-tag:
  extends: qemu-hexagon-linux-aarch64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

# QEMU AArch64 for Linux on x86_64
qemu-aarch64-linux-x86_64:
  extends: .build-job
  variables:
    QUIC_BUILD_CONFIG: aarch64

qemu-aarch64-linux-x86_64-tag:
  extends: qemu-aarch64-linux-x86_64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

release:
  stage: .post
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: qemu-hexagon-linux-x86_64-tag
      artifacts: true
    - job: qemu-hexagon-linux-aarch64-tag
      artifacts: true
    - job: qemu-hexagon-macOS-tag
      artifacts: true
    - job: qemu-hexagon-windows-x86_64-tag
      artifacts: true
  script: ./quic-gitlab-ci.d/release.sh
