image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest

workflow:
  auto_cancel:
    on_job_failure: all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_TAG

variables:
  FF_SCRIPT_SECTIONS: True
  GIT_DEPTH: 1

  HEX_COPROC_REF: v10.2.3

checkpatch:
  stage: .pre
  variables:
    GIT_DEPTH: 50
    GIT_FETCH_EXTRA_FLAGS: --filter=blob:none --filter=tree:0 --prune --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script: quic-gitlab-ci.d/checkpatch.sh
  timeout: 5 minutes

user_guide:
  stage: build
  script:
    - make -C quic/user_guide/ html latexpdf
  artifacts:
    paths: [ quic/user_guide/_build/html, quic/user_guide/_build/latex ]
    expire_in: 1 days

# QEMU Hexagon for Linux on x86_64
hexagon-linux-x86_64:
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -j linux-x86-tag -r $HEX_COPROC_REF hexagon,linux-x86_64
  artifacts:
    paths: [ build ]
    expire_in: 1 day

hexagon-linux-x86_64-tag:
  extends: hexagon-linux-x86_64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

hexagon-linux-x86_64-check-tcg:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-check-tcg.sh

hexagon-linux-x86_64-check-tcg-mttcg:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-check-tcg.sh -m

hexagon-linux-x86_64-check:
  stage: test
  tags: [ new-libseccomp ]
  dependencies:
    - hexagon-linux-x86_64
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose

hexagon-linux-x86_64-qurt:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_qurt

hexagon-linux-x86_64-sival:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_sival

hexagon-linux-x86_64-boot:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_linux

hexagon-linux-x86_64-virtio:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_virtio

hexagon-linux-x86_64-perf:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  tags:
    - performance-hardware
  script: quic-gitlab-ci.d/scripts/hexagon-linux-x86_64-perf.sh
  artifacts:
    paths: [ "perf-results.json" ]
    expire_in: 4 days

hexagon-linux-x86_64-perf-mttcg:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  tags:
    - performance-hardware
  script: quic-gitlab-ci.d/scripts/hexagon-linux-x86_64-perf-mttcg.sh
  artifacts:
    paths: [ "perf-results.json" ]
    expire_in: 4 days

hexagon-linux-x86_64-perf-ml:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u24:latest
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  tags:
    - performance-hardware
  script: quic-gitlab-ci.d/scripts/hexagon-linux-x86_64-perf-ml.sh
  artifacts:
    when: always
    paths: [ "perf-results.json",  ]
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

# QEMU Hexagon for Linux on x86_64 with sanatizers enabled
hexagon-linux-x86_64-san:
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -j linux-x86-tag -r $HEX_COPROC_REF hexagon,linux-x86_64,san
  artifacts:
    paths: [ build ]
    expire_in: 1 day

hexagon-linux-x86_64-san-check-tcg:
  stage: test
  dependencies:
    - hexagon-linux-x86_64
  script: quic/scripts/run-check-tcg.sh

hexagon-linux-x86_64-san-check:
  stage: test
  tags: [ new-libseccomp ]
  dependencies:
    - hexagon-linux-x86_64-san
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose

hexagon-linux-x86_64-san-qurt:
  stage: test
  dependencies:
    - hexagon-linux-x86_64-san
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_qurt

hexagon-linux-x86_64-san-sival:
  stage: test
  dependencies:
    - hexagon-linux-x86_64-san
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_sival

hexagon-linux-x86_64-san-boot:
  stage: test
  dependencies:
    - hexagon-linux-x86_64-san
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_linux

hexagon-linux-x86_64-san-virtio:
  stage: test
  dependencies:
    - hexagon-linux-x86_64-san
  script: quic/scripts/run-functional-test.sh func-hexagon-hexagon_virtio

# QEMU Hexagon for macOS
hexagon-mac:
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -j mac-tag -r $HEX_COPROC_REF hexagon,mac
  artifacts:
    paths: [ build ]
    expire_in: 1 day
  tags:
    - mac

hexagon-mac-tag:
  extends: hexagon-mac
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

# QEMU Hexagon for Windows on x86_64
hexagon-windows-x86_64:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-win:latest
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -p windows-x86_64 -s quic/install_win_deps.bat hexagon,windows-x86_64
  artifacts:
    paths: [ build ]
    expire_in: 1 day

hexagon-windows-x86_64-tag:
  extends: hexagon-windows-x86_64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

hexagon-windows-x86_64-check-tcg:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-win:latest
  stage: test
  dependencies:
    - hexagon-windows-x86_64
  script: quic/scripts/run-check-tcg.sh

# QEMU Hexagon for Windows on aarch64
hexagon-windows-aarch64:
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-win-aarch64:latest
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -p windows-aarch64 -s quic/install_win_aarch64_deps.bat hexagon,windows-aarch64
  artifacts:
    paths: [ build ]
    expire_in: 1 day

hexagon-windows-aarch64-tag:
  extends: hexagon-windows-aarch64
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never

# QEMU Hexagon for Linux on x86_64 without idef parser
hexagon-linux-x86_64-no-idef-parser:
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh -j linux-x86-tag -r $HEX_COPROC_REF hexagon,linux-x86_64,no-idef-parser
  artifacts:
    paths: [ build ]
    expire_in: 1 day
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

hexagon-linux-x86_64-no-idef-parser-check-tcg:
  stage: test
  dependencies:
    - hexagon-linux-x86_64-no-idef-parser
  script: quic/scripts/run-check-tcg.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

hexagon-linux-x86_64-no-idef-parser-check:
  stage: test
  tags: [ new-libseccomp ]
  dependencies:
    - hexagon-linux-x86_64-no-idef-parser
  script: ./build/pyvenv/bin/meson test -C build --no-rebuild --verbose
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

# QEMU Hexagon for Linux on aarch64
aarch64-linux:
  stage: build
  script: quic-gitlab-ci.d/scripts/build.sh aarch64,linux-x86_64
  artifacts:
    paths: [ build ]
    expire_in: 1 day

aarch64-linux-tag:
  extends: aarch64-linux
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: never
