##
##  Copyright(c) 2019-2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
##
##  This program is free software; you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation; either version 2 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, see <http://www.gnu.org/licenses/>.
##

# -*- Mode: makefile -*-
#
# Hexagon SoftMMU tests - included from tests/tcg/Makefile
#

HEXAGON_SYSTEM_SRC=$(SRC_PATH)/tests/tcg/hexagon/system

# Set search path for all sources
VPATH 		+= $(HEXAGON_SYSTEM_SRC)

########### Compiling options
CC=hexagon-unknown-linux-musl-clang
# We force -O0 to avoid optimizations that would break the
# libc simplifications we made at min_libc.c
#
CFLAGS=-mv73 -G0 -nodefaultlibs -nostdlib -static -fno-PIC -O0 -Werror
LDFLAGS=-lclang_rt.builtins-hexagon

########### QEMU options
QEMU_BASE_MACHINE=-M virt -cpu any,count-gcycle-xt=on,cacheop-exceptions=true,usefs=$(SRC_PATH)/tests/tcg/hexagon/system
QEMU_OPTS+=-display none
QEMU_EXTRA_OPTS=
# Set this before running make if you want to run tests with specific options,
# such as MTTCG.
OVERRIDE_OPTS?=
QEMU_OPTS+=$(QEMU_BASE_MACHINE) $(QEMU_EXTRA_OPTS) $(OVERRIDE_OPTS) -kernel
PARANOID_OPTS=-cpu any,paranoid-commit-state=true

crt0.o: crt0/crt0.S crt0/crt0.inc
crt0_standalone.o: crt0/crt0_standalone.S crt0/crt0.inc
pte.o: crt0/pte.S
min_libc.o: crt0/min_libc.c
tlb.o: crt0/tlb.c

CRT0_OBJS=crt0.o crt0_standalone.o pte.o min_libc.o tlb.o

TESTS += \
	mmu_page_size \
	mmu_overlap \
	standalone_vec \
	standalone_hw \
	mmu_asids \
	semihost \
	ciad-siad \
	udma \
	vid_reg \
	int_range \
	hvx-multi \
	tlb-miss-tlblock \
	badva \
	fastl2vic \
	$()

$(TESTS): $(CRT0_OBJS)

include $(SRC_PATH)/tests/tcg/hexagon/Makefile.quic-softmmu-target

# Build and link the tests
echo-and-run = echo $(1) && $(1)
define build_fn
    @if test "$(3)" = LINK; then extra="$(LDFLAGS)"; else extra=-c; fi && \
    $(call echo-and-run, $(CC) $(CFLAGS) $(EXTRA_TEST_CFLAGS) \
        $(1) -o $(2) $$extra)
endef

$(CRT0_OBJS):
	$(call build_fn,$<,$@)
$(TESTS):
	$(call build_fn,$^,$@,LINK)

%.o: %.S
	$(call build_fn,$<,$@)
%.o: %.c
	$(call build_fn,$<,$@)
%.o: %.cpp
	$(call build_fn,$<,$@)

mmu.h: ../hex_test.h
invalid_opcode.h: mmu.h

mmu_page_size.o: mmu_page_size.c mmu.h
mmu_page_size: mmu_page_size.o dummy_mutex.o
standalone_hw: standalone_hw.o monitor_insts.o
standalone_vec.o: standalone_vec.c cfgtable.h
standalone_vec: standalone_vec.o
mmu_overlap.o: mmu_overlap.c mmu.h
mmu_overlap: mmu_overlap.o dummy_mutex.o
mmu_asids.o: mmu_asids.c mmu.h
mmu_asids: mmu_asids.o dummy_mutex.o
mmu_cacheops.o: mmu_cacheops.c mmu.h
ciad-siad: ciad-siad.o
udma: udma.o
udma.o: udma.c dma.h
vid_reg: vid_reg.o
int_range.o: int_range.c cfgtable.h
int_range: int_range.o
semihost.o: semihost.c strutils.h
semihost: semihost.o
hvx-multi.o: hvx-multi.c ../hvx_misc.h
hvx-multi: hvx-multi.o
badva.o: badva.c ../hex_test.h crt0/hexagon_standalone.h
badva: badva.o
fastl2vic.o: fastl2vic.c cfgtable.h
fastl2vic: fastl2vic.o

############# Custom build options

standalone_vec.o: CFLAGS+= -mv69 -O2 -mhvx  -fvectorize
hvx-multi.o: CFLAGS+= -O2 -mhvx

# We don't want to link this one with crt0 files
tlb-miss-tlblock: tlb-miss-tlblock.o
	$(CC) $(CFLAGS) $< -o $@ -nostartfiles -Wl,-Ttext,0x9b800000 -Wl,-entry,0x9b800000

############# Custom test rules

run-standalone_hw: standalone_hw
run-standalone_vec: standalone_vec
run-standalone_hw run-standalone_vec:
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $<, "$< on $(TARGET_NAME)")
	$(call run-test, $<, $(QEMU) $(PARANOID_OPTS) -kernel $<, "$< on $(TARGET_NAME) paranoid")
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $< -M SA8540P_CDSP0,"$< on $(TARGET_NAME) cdsp0")
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $< -M SA8775P_CDSP0,"$< on $(TARGET_NAME) cdsp0")

run-semihost: semihost
	mkdir -p _semihost_dir
	touch _semihost_dir/fileA _semihost_dir/fileB
	$(call run-test, $<, $(QEMU) --append "arg1 arg2" $(QEMU_OPTS) $< \
		             > $<.stdout)
	$(call quiet-command, grep -q "PASS" $<.stdout, "GREP", "PASS")
