##
##  Copyright(c) 2019-2025 Qualcomm Innovation Center, Inc. All Rights Reserved.
##
##  This program is free software; you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation; either version 2 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, see <http://www.gnu.org/licenses/>.
##

# -*- Mode: makefile -*-
#
# Hexagon SoftMMU tests - included from tests/tcg/Makefile
#

HEXAGON_SYSTEM_SRC=$(SRC_PATH)/tests/tcg/hexagon/system

# Set search path for all sources
VPATH 		+= $(HEXAGON_SYSTEM_SRC)

########### Compiling options
CC=hexagon-unknown-linux-musl-clang
# We force -O0 to avoid optimizations that would break the
# libc simplifications we made at min_libc.c
#
CFLAGS=-mv73 -G0 -nodefaultlibs -nostdlib -static -fno-PIC -O0 -g -Werror
LDFLAGS=-lclang_rt.builtins-hexagon

########### QEMU options
QEMU_BASE_MACHINE=-M V66G_1024 -semihosting-config usefs=$(SRC_PATH)/tests/tcg/hexagon/system
QEMU_OPTS+=-display none

QEMU_OPTS+=$(QEMU_BASE_MACHINE) -kernel

crt0.o: crt0/crt0.S crt0/crt0.inc
crt0_standalone.o: crt0/crt0_standalone.S crt0/crt0.inc
pte.o: crt0/pte.S
min_libc.o: crt0/min_libc.c
tlb.o: crt0/tlb.c

CRT0_OBJS=crt0.o crt0_standalone.o pte.o min_libc.o tlb.o

TESTS += \
	semihost \
	$()

$(TESTS): $(CRT0_OBJS)

# Build and link the tests
echo-and-run = echo $(1) && $(1)
define build_fn
    @if test "$(3)" = LINK; then extra="$(LDFLAGS)"; else extra=-c; fi && \
    $(call echo-and-run, $(CC) $(CFLAGS) $(1) -o $(2) $$extra)
endef

$(CRT0_OBJS):
	$(call build_fn,$<,$@)
$(TESTS):
	$(call build_fn,$^,$@,LINK)

%.o: %.S
	$(call build_fn,$<,$@)
%.o: %.c
	$(call build_fn,$<,$@)

semihost.o: semihost.c strutils.h
semihost: semihost.o

############# Custom test rules

run-semihost: semihost
	mkdir -p _semihost_dir
	touch _semihost_dir/fileA _semihost_dir/fileB
	$(call run-test, $<, $(QEMU) --append "arg1 arg2" $(QEMU_OPTS) $< \
		             > $<.stdout)
	$(call quiet-command, grep -q "PASS" $<.stdout, "GREP", "PASS")
