#  Copyright(c) 2019-2026 Qualcomm Innovation Center, Inc. All Rights Reserved.
#  SPDX-License-Identifier: GPL-2.0-or-later

HEXAGON_SYSTEM_SRC=$(SRC_PATH)/tests/tcg/hexagon/system

# Set search path for all sources
VPATH 		+= $(HEXAGON_SYSTEM_SRC)

########### Compiling options
CFLAGS=-target hexagon-unknown-none-elf -mv73 -G0 -O2 -static -Werror

########### QEMU options
QEMU_BASE_MACHINE=-M sim -cpu any,count-gcycle-xt=on,cacheop-exceptions=true,usefs=$(SRC_PATH)/tests/tcg/hexagon/system
QEMU_OPTS+=-display none
QEMU_EXTRA_OPTS=

# Set this before running make if you want to run tests with specific options,
# such as MTTCG.
OVERRIDE_OPTS?=
QEMU_OPTS+=$(QEMU_BASE_MACHINE) $(QEMU_EXTRA_OPTS) $(OVERRIDE_OPTS) -kernel

TESTS += \
	tlb-miss-tlblock \
	$()

CPU_LIST=$(shell $(QEMU) -cpu help | grep 'v[0-9][0-9]*')

# These softmmu-only test rules and runners are skipped for Windows cross builds.
ifeq (,$(findstring w64,$(CROSS_PREFIX)))

TESTS += ieee_fp coproc_conv coproc_conv_fp16 coproc_range

ieee_fp: ieee_fp.o
coproc: coproc.o
coproc.o: coproc.c coproc_ref.h
coproc_conv.o: coproc_conv.c coproc_common.h coproc_conv_asm.h \
	       coproc_input_dat.h coproc_ref_output_dat.h util.h \
	       vtcm_common.h
coproc_conv: coproc_conv.o coproc_conv_asm.o util.o
coproc_conv_fp16.o: coproc_conv_fp16.cpp coproc_common.h \
	            coproc_input_fp16_dat.h coproc_ref_output_fp16_dat.h \
		    vtcm_common.h
coproc_conv_fp16: coproc_conv_fp16.o
coproc_range: coproc_range.o

ieee_fp.o: EXTRA_TEST_CFLAGS= -mhvx -mhvx-length=128B -mhvx-ieee-fp
coproc coproc.o: EXTRA_TEST_CFLAGS= -mhmx -mv81
coproc_conv.o: EXTRA_TEST_CFLAGS= -mhmx
coproc_conv_asm.o: EXTRA_TEST_CFLAGS= -mhmx
coproc_conv_fp16.o: EXTRA_TEST_CFLAGS= -mhmx
coproc_range.o: EXTRA_TEST_CFLAGS= -mhmx

run-coproc:QEMU_EXTRA_OPTS=-M sim_coproc
run-coproc_conv:QEMU_EXTRA_OPTS=-M sim_coproc
run-coproc_range:QEMU_EXTRA_OPTS=-M V68N_1024
run-coproc_conv_fp16:QEMU_EXTRA_OPTS=-M sim_coproc

run-vid-group: vid-group
run-swi_wait: swi_wait
run-tlblock: tlblock
run-vid-group: vid-group
run-coproc:coproc
run-coproc_conv: coproc_conv
run-coproc_range: coproc_range

run-gregs: gregs
	$(call run-test, $<, $(QEMU) -d unimp $(QEMU_OPTS) $< 2> _$<.stderr, \
		"$< on $(TARGET_NAME)") || { cat _$<.stderr; exit 1; }
	grep -E 'Warning: (guest register|ignoring write to guest register)' \
		_$<.stderr > _$<.stderr.filtered
	diff $(HEXAGON_SYSTEM_SRC)/expected-gregs-warnings.txt _$<.stderr.filtered

# Test combinations, with expected output separated by a ':'
#
REV_TEST_COMBINATIONS="-M V69NA_1024           : 0x69" \
		      "-cpu any                : 0x73" \
		      "-cpu v69                : 0x69" \
		      "-cpu v73 -M V69NA_1024  : 0x73" \
		      "-cpu v69 -M V73NA_1024  : 0x69" \
		      "-cpu any -M V69NA_1024  : 0x69" \
		      "-cpu any -M V73NA_1024  : 0x73"

run-rev: rev
	@i=0; \
	ret=0; \
	for comb in $(REV_TEST_COMBINATIONS); do \
		opt="$$(echo "$$comb" | cut -d: -f1)"; \
		exp="$$(echo "$$comb" | cut -d: -f2)"; \
		echo "$< on $(TARGET_NAME) ($$i)"; \
		( \
			if test -n "$(V)"; then set -x; fi; \
			$(QEMU) $(QEMU_OPTS) $< $$opt >$@.$$i.out 2>$@.$$i.err  \
		) && \
		grep -qF $$exp $@.$$i.out; \
		err=$$?; \
		if test $$exp != 0x73; then \
			grep -q 'warning: using .* cpu but binary is for v73' $@.$$i.err; \
			err=$$(($$err + $$?)); \
		fi; \
		if test $$err -eq 0; then \
			echo "  rev test $$i: OK"; \
		else \
			echo "  rev test $$i: FAIL"; \
			ret=1; \
		fi; \
		i=$$(($$i + 1)); \
	done; \
	exit $$ret

# Run selected tests a second time with icount when OVERRIDE_OPTS is unset.

ifeq ($(OVERRIDE_OPTS),)
run-test-extra = $(call run-test, $1, $2, $3)
else
# If OVERRIDE_OPTS is defined, we skip tests using custom options that
# could interfere with OVERRIDE_OPTS
define run-test-extra
	echo "WARNING: OVERRIDE_OPTS defined, SKIPPING '$3'"
endef
endif

ICOUNT_OPTS=-icount auto
run-tlblock run-swi_wait run-vid-group:
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS) $<,"$< on $(TARGET_NAME)")
	$(call run-test-extra, $<, $(QEMU) $(QEMU_OPTS) $< $(ICOUNT_OPTS),"$< on $(TARGET_NAME) icount")

run-coproc_conv_fp16: coproc_conv_fp16
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)  $< --append "2 2 2 coproc_input_fp16.dat coproc_output_fp16.dat","$< on $(TARGET_NAME)")

# hexagon-lldb starts qemu with an empty environment. To bypass that, we create
# a wrapper script which properly sets the environment before invoking qemu.
ifneq ($(HAVE_HEXAGON_LLDB_BIN),)
.PHONY: FORCE
qemu-wrapper-for-lldb: FORCE
	{ echo '#!/bin/bash' && \
	  export -p && \
	  echo '"$(QEMU)"' '"$$@"'; } >$@ && \
	chmod +x $@

run-and-check-pass = $(call run-test, $1, \
	bash -c "{ $2 | tee /dev/fd/8 $1.out | grep -q '^PASS$$'; } 8>&1", $3)

run-lldb = $(call run-and-check-pass, $1, \
	     $(HAVE_HEXAGON_LLDB_BIN) --no-lldbinit --batch \
	     --source $(HEXAGON_SYSTEM_SRC)/lldbscripts/$2 \
	     $< -- $(filter-out -kernel,$(QEMU_OPTS)), $3)

run-lldb-revcon run-lldb-reg-reads run-lldb-reg-writes: export LLDB_HEXAGON_USE_QEMU = 1
run-lldb-revcon run-lldb-reg-reads run-lldb-reg-writes: export LLDB_HEXAGON_QEMU_PATH = qemu-wrapper-for-lldb

run-lldb-revcon: simple-assign qemu-wrapper-for-lldb
	$(call run-lldb,$@,test-revcon.lldb,"basic qemu revcon test")

reg-reads: reg-reads.o
reg-reads.o: reg-reads.c timer.h pmu.h
reg-reads.o: EXTRA_TEST_CFLAGS=-DCSR_BASE=0xfc900000 -mhvx -O0 -g
reg-reads: EXTRA_TEST_CFLAGS=-O0 -g

run-lldb-reg-reads: reg-reads qemu-wrapper-for-lldb
	$(call run-lldb,$@,test-reg-reads.lldb,"gdbstub reg reading test")
	$(call quiet-command, grep -q "r00* = 0xdeadbeef" $@.out, "GREP", "gpr");
	$(call quiet-command, awk '!/timerlo = 0x[0]{8}/ && /timerlo = 0x[0-9a-f]{8}/' $@.out, "GREP", "sreg");
	$(call quiet-command, grep -q "gpmucnt0 = 0x00000002" $@.out, "GREP", "greg");
	$(call quiet-command, grep -q "upmucnt0 = 0x00000002" $@.out, "GREP", "creg");

run-lldb-reg-writes: reg-writes qemu-wrapper-for-lldb
	$(call run-lldb,$@,test-reg-writes.lldb,"gdbstub reg writing test")

EXTRA_RUNS += run-lldb-revcon run-lldb-reg-reads run-lldb-reg-writes
endif # have LLDB
endif

simple-assign reg-reads reg-writes:
	$(CC) $(CFLAGS) $(EXTRA_TEST_CFLAGS) $^ -o $@ $(LDFLAGS)

# Args: cutoff_cpu_rev, test_name, dependency_list
define test_comp_for_each_cpu
@for cpu in $(CPU_LIST); do \
    if test "$${cpu##v}" -ge $1; then \
        $(CC) $(CFLAGS) -mhvx -m$$cpu $3 \
		-o $2-$$cpu $(LDFLAGS) || exit 1; \
    fi; \
done && touch $2; #So that make won't rebuild this everytime
endef

# Args: cutoff_cpu_rev, test_name
define test_for_each_cpu
@for cpu in $(CPU_LIST); do \
    if test "$${cpu##v}" -ge $1; then \
        echo "TEST $2 on $$cpu"; \
        timeout -s KILL --foreground $(TIMEOUT) $(QEMU) $(QEMU_BASE_MACHINE) \
		-cpu $$cpu $(OVERRIDE_OPTS) -kernel $2-$$cpu || exit 1; \
    fi; \
done;
endef

hvx_ext-sys: hvx_ext.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))
hvx-multi-sys: hvx-multi.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))
hvx_misc-sys: ../hvx_misc.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))

run-hvx_ext-sys: hvx_ext-sys
	$(call test_for_each_cpu, 75, $<)
run-hvx-multi-sys: hvx-multi-sys
	$(call test_for_each_cpu, 75, $<)
run-hvx_misc-sys: hvx_misc-sys
	$(call test_for_each_cpu, 75, $<)

EXTRA_RUNS += run-hvx_ext-sys run-hvx-multi-sys run-hvx_misc-sys

simple-assign: simple-assign.o
reg-writes: reg-writes.o
reg-writes.o: reg-writes.c

reg-writes.o: EXTRA_TEST_CFLAGS=-O0 -g
reg-writes: EXTRA_TEST_CFLAGS=-O0 -g

# Build and link the tests
echo-and-run = echo $(1) && $(1)
define build_fn
    @if test "$(3)" = LINK; then extra="$(LDFLAGS)"; else extra=-c; fi && \
    $(call echo-and-run, $(CC) $(CFLAGS) $(EXTRA_TEST_CFLAGS) \
        $(1) -o $(2) $$extra)
endef

$(TESTS):
	$(call build_fn,$^,$@,LINK)

%.o: %.S
	$(call build_fn,$<,$@)
%.o: %.c
	$(call build_fn,$<,$@)
%.o: %.cpp
	$(call build_fn,$<,$@)

############# Custom build options

# tlb-miss-tlblock is a baremetal binary with no libc dependencies.
# We don't want to link it with crt0 files.  When the linux-musl
# driver is used (the default for both hexagon-softmmu and
# hexagon-linux-user) -target hexagon-unknown-none-elf selects the
# bare-elf toolchain class, which emits the same baremetal link
# line as the SDK's hexagon-clang.
tlb-miss-tlblock.o: tlb-miss-tlblock.S
	$(CC) $(CFLAGS) -c $< -o $@

tlb-miss-tlblock: tlb-miss-tlblock.o
	$(CC) $(CFLAGS) $< -o $@ -nostartfiles -Wl,-Ttext,0x9b800000 -Wl,-entry,0x9b800000
