##
##  Copyright(c) 2019-2023 Qualcomm Innovation Center, Inc. All Rights Reserved.
##
##  This program is free software; you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation; either version 2 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, see <http://www.gnu.org/licenses/>.
##

# Hexagon doesn't support gdb, so skip the EXTRA_RUNS
EXTRA_RUNS =

CFLAGS = -mv69 -O2 -mhvx -fvectorize
CFLAGS += -Wno-incompatible-pointer-types -Wno-undefined-internal
CFLAGS += -Wno-unknown-warning-option -Wno-error=unused-but-set-global
CFLAGS += -fno-unroll-loops -fno-stack-protector

HEX_SRC=$(SRC_PATH)/tests/tcg/hexagon
VPATH += $(HEX_SRC)

invalid_vhist: $(HEX_SRC)/invalid_vhist.S
	$(CC) -static -mv69 -mhvx -nostdlib $^ -o $@
%: $(HEX_SRC)/%.S $(HEX_SRC)/crt.S
	$(CC) -static -mv69 -nostdlib $^ -o $@

HEX_TESTS = first
HEX_TESTS += invalid_vhist
HEX_TESTS += hex_sigsegv
HEX_TESTS += misc
HEX_TESTS += usr
HEX_TESTS += preg_alias
HEX_TESTS += dual_stores
HEX_TESTS += clrtnew
HEX_TESTS += pred_stores
HEX_TESTS += multi_result
HEX_TESTS += mem_noshuf
HEX_TESTS += mem_noshuf_exception
HEX_TESTS += circ
HEX_TESTS += brev
HEX_TESTS += load_unpack
HEX_TESTS += load_align
HEX_TESTS += fpstuff
HEX_TESTS += overflow
HEX_TESTS += hvx_misc
HEX_TESTS += gp_rel
HEX_TESTS += pthread_cancel
HEX_TESTS += read_write_overlap
HEX_TESTS += vector_add_int
HEX_TESTS += scatter_gather
HEX_TESTS += atomics
HEX_TESTS += sfminmax
HEX_TESTS += lsbnew
HEX_TESTS += privcheck
HEX_TESTS += guestcheck
HEX_TESTS += hvx_histogram
HEX_TESTS += hvx_sat
HEX_TESTS += usr_ctrl_assign
HEX_TESTS += signal_context
HEX_TESTS += reg_mut
HEX_TESTS += scalar
HEX_TESTS += upcycle
HEX_TESTS += pmpyw
HEX_TESTS += utimer

TESTS += $(HEX_TESTS)

usr_ctrl_assign: usr_ctrl_assign.c usr_ctrl_assign_pass.S
	$(CC) $(CFLAGS) $(CROSS_CC_GUEST_CFLAGS) $^ -o $@ $(LDFLAGS)

reg_mut: reg_mut.h

# Run some tests with paranoid-commit-state turned on
run-misc: misc
run-usr: usr
run-preg_alias: preg_alias
run-dual_stores: dual_stores
run-pred_stores: pred_stores
run-multi_result: multi_result
run-mem_noshuf: mem_noshuf
run-hvx_misc: hvx_misc
run-scatter_gather: scatter_gather
run-hvx_histogram: hvx_histogram
run-hvx_sat: hvx_sat
run-hvx-bitmode: hvx_sat
	$(call run-test-neg, $<, $(QEMU) -cpu v66 $<, "$< on $(TARGET_NAME) v66")
	$(call run-test, $<, $(QEMU) -cpu v67 $<, "$< on $(TARGET_NAME) v67")
	$(call run-test, $<, $(QEMU) -cpu any $<, "$< on $(TARGET_NAME) any")


PARANOID_OPTS=-cpu v73,paranoid-commit-state=true
IN_ASM_OPTS=-d in_asm
run-misc run-usr run-preg_alias run-dual_stores run-pred_stores run-multi_result run-mem_noshuf \
run-hvx_misc run-scatter_gather run-hvx_histogram run-hvx_sat:
	$(call run-test, $<, $(QEMU) $<, "$< on $(TARGET_NAME)")
	$(call run-test, $<, $(QEMU) $(PARANOID_OPTS) $<, "$< on $(TARGET_NAME) paranoid")
	$(call run-test, $<, $(QEMU) $(IN_ASM_OPTS) -D $<.in_asm $<, "$< on $(TARGET_NAME) in_asm")

# These tests raise an exception and return 1 to the shell
# We'll grep for the proper exception number in their stderr
run-privcheck: privcheck
run-guestcheck: guestcheck

run-privcheck:
	$(call run-test, $<, $(QEMU) $< 2> $<.stderr,"$< on $(TARGET_NAME)"); \
	if [ $$? -ne 1 ] ; then \
		return 1; \
	fi
	$(call quiet-command, \
		grep -q "exception 0x1b" $<.stderr, \
		"GREP", "exception 0x1b");

run-guestcheck:
	$(call run-test, $<, $(QEMU) $< 2> $<.stderr,"$< on $(TARGET_NAME)"); \
	if [ $$? -ne 1 ] ; then \
		return 1; \
	fi
	$(call quiet-command, \
		grep -q "exception 0x1a" $<.stderr, \
		"GREP", "exception 0x1a");

HEX_TESTS += invalid-slots
HEX_TESTS += invalid-encoding
HEX_TESTS += unaligned_pc
HEX_TESTS += multiple-writes
HEX_TESTS += invalid-immext
HEX_TESTS += test_abs
HEX_TESTS += test_bitcnt
HEX_TESTS += test_bitsplit
HEX_TESTS += test_call
HEX_TESTS += test_clobber
HEX_TESTS += test_cmp
HEX_TESTS += test_dotnew
HEX_TESTS += test_ext
HEX_TESTS += test_fibonacci
HEX_TESTS += test_hl
HEX_TESTS += test_hwloops
HEX_TESTS += test_jmp
HEX_TESTS += test_lsr
HEX_TESTS += test_mpyi
HEX_TESTS += test_packet
HEX_TESTS += test_reorder
HEX_TESTS += test_round
HEX_TESTS += test_vavgw
HEX_TESTS += test_vcmpb
HEX_TESTS += test_vcmpw
HEX_TESTS += test_vlsrw
HEX_TESTS += test_vmaxh
HEX_TESTS += test_vminh
HEX_TESTS += test_vpmpyh
HEX_TESTS += test_vspliceb

HEX_TESTS += check_rev_gating
HEX_TESTS += test_pnew_jump_loads

HEX_TESTS += v68_hvx
HEX_TESTS += v69_hvx

TESTS += $(HEX_TESTS)

atomics: atomics.c hex_test.h
brev: brev.c hex_test.h
circ: circ.c hex_test.h
dual_stores: dual_stores.c hex_test.h
fpstuff: fpstuff.c hex_test.h
hex_sigsegv: hex_sigsegv.c hex_test.h
load_align: load_align.c hex_test.h
load_unpack: load_unpack.c hex_test.h
mem_noshuf_exception: mem_noshuf_exception.c hex_test.h
mem_noshuf: mem_noshuf.c hex_test.h
misc: misc.c hex_test.h
multi_result: multi_result.c hex_test.h
overflow: overflow.c hex_test.h
preg_alias: preg_alias.c hex_test.h
read_write_overlap: read_write_overlap.c hex_test.h
reg_mut: reg_mut.c hex_test.h
test_pnew_jump_loads: test_pnew_jump_loads.c hex_test.h
unaligned_pc: unaligned_pc.c
utimer: utimer.c hex_test.h

# Compile for v66 so that the ELF selects a v66 CPU; the test then
# exercises revision gating by executing a v68 .word instruction.
run-check_rev_gating: QEMU_OPTS += -cpu v66
check_rev_gating: check_rev_gating.c

# The test exercises revision gating by executing a v68 .word instruction on
# a v66 cpu.
#
# NOTE: The static musl toolchain libraries are compiled for v68, so even
# with -mv66 the linker sets ELF flags to v68 (max of all inputs). We must
# force -cpu v66 at runtime to test the revision gating.
run-check_rev_gating: check_rev_gating
	$(call run-test, $<, env QEMU=$(QEMU) $(QEMU) -cpu v66 $(QEMU_OPTS) $<)

# Older clang versions don't support -maudio.  Detect support so the
# test still compiles on those toolchains; the audio-specific code in
# usr.c is guarded by defined(__HEXAGON_AUDIO__) and will simply be
# skipped when -maudio is absent.
HEXAGON_AUDIO_FLAG := $(shell $(CC) -E -maudio - </dev/null >/dev/null 2>&1 && echo -maudio)

usr: usr.c hex_test.h
	$(CC) $(CFLAGS) $(HEXAGON_AUDIO_FLAG) -O2 $< -o $@ $(LDFLAGS) \
		-Wno-inline-asm -Wno-expansion-to-defined -Wl,--no-warn-mismatch

# Build this test with -mv71 to exercise the CABAC instruction
misc: misc.c
	$(CC) $(CFLAGS) -mv71 -O2 $< -o $@ $(LDFLAGS)

# This test uses a v79 instruction encoded with .word
scalar: scalar.S crt.S
	$(CC) $(CFLAGS) -nostdlib -mv79 -O2 $< -o $@ $(LDFLAGS)

scatter_gather: CFLAGS += -mhvx
vector_add_int: CFLAGS += -mhvx -fvectorize
hvx_misc: hvx_misc.c hvx_misc.h
hvx_misc: CFLAGS += -mhvx
hvx_histogram: CFLAGS += -mhvx -Wno-gnu-folding-constant
v68_hvx: v68_hvx.c hvx_misc.h v6mpy_ref.c.inc
v68_hvx: CFLAGS += -mhvx -Wno-unused-function
v69_hvx: v69_hvx.c hvx_misc.h
v69_hvx: CFLAGS += -mhvx -Wno-unused-function

hvx_histogram: hvx_histogram.c hvx_histogram_row.S
	$(CC) $(CFLAGS) $(CROSS_CC_GUEST_CFLAGS) $^ -o $@ $(LDFLAGS)

ifeq ($(CONFIG_PLUGIN),y)
# LLVM is way too aggressive with inlining and dead code elimination even at
# -O0, which interferes with the test. What looks like dead code in this test
# to the compiler isn't actually dead code, so we need to disable all potential
# LLVM optimization passes.
test-plugin-set-pc: CFLAGS += -Xclang -disable-llvm-passes
endif
