##
##  Copyright(c) 2019-2025 Qualcomm Innovation Center, Inc. All Rights Reserved.
##
##  SPDX-License-Identifier: GPL-2.0-or-later
##

# -*- Mode: makefile -*-

CPU_LIST=$(shell $(QEMU) -cpu help | grep 'v[0-9][0-9]*')

# We skip these tests for windows builds
ifeq (,$(findstring w64,$(CROSS_PREFIX)))
include $(SRC_PATH)/tests/tcg/hexagon/Makefile.quic-softmmu-target-linux
endif

simple-assign reg-reads reg-writes:
	$(CC) $(CFLAGS) $(EXTRA_TEST_CFLAGS) $^ -o $@ $(LDFLAGS)

# Args: cutoff_cpu_rev, test_name, dependency_list
define test_comp_for_each_cpu
@for cpu in $(CPU_LIST); do \
    if test "$${cpu##v}" -ge $1; then \
        $(CC) $(CFLAGS) -mhvx -m$$cpu $3 \
		-o $2-$$cpu $(LDFLAGS) || exit 1; \
    fi; \
done && touch $2; #So that make won't rebuild this everytime
endef

# Args: cutoff_cpu_rev, test_name
define test_for_each_cpu
@for cpu in $(CPU_LIST); do \
    if test "$${cpu##v}" -ge $1; then \
        echo "TEST $2 on $$cpu"; \
        timeout -s KILL --foreground $(TIMEOUT) $(QEMU) $(QEMU_BASE_MACHINE) \
		-cpu $$cpu $(OVERRIDE_OPTS) -kernel $2-$$cpu || exit 1; \
    fi; \
done;
endef

hvx_ext-sys: hvx_ext.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))
hvx-multi-sys: hvx-multi.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))
hvx_misc-sys: ../hvx_misc.c ../hvx_misc.h
	$(call test_comp_for_each_cpu, 75, $@, $(filter %.c %.s,$^))

run-hvx_ext-sys: hvx_ext-sys
	$(call test_for_each_cpu, 75, $<)
run-hvx-multi-sys: hvx-multi-sys
	$(call test_for_each_cpu, 75, $<)
run-hvx_misc-sys: hvx_misc-sys
	$(call test_for_each_cpu, 75, $<)

EXTRA_RUNS += run-hvx_ext-sys run-hvx-multi-sys run-hvx_misc-sys

simple-assign: simple-assign.o
reg-writes: reg-writes.o
reg-writes.o: reg-writes.c

reg-writes.o: EXTRA_TEST_CFLAGS=-O0 -g
reg-writes: EXTRA_TEST_CFLAGS=-O0 -g
