# graphics device
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('graphics.c'))

# gpu
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('gpu.c'))
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('kgsl.c'))
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('rscc.c'))
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('cx_dbgc.c'))
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('cx_misc.c'))

# gmu
system_ss.add(when: 'CONFIG_QCOM_GRAPHICS', if_true: files('gmu.c'))

