[package]
name = "gpu"
version = "0.1.0"
edition = "2021"
authors = ["Romain Malmain <rmalmain@qti.qualcomm.com>"]
license = "GPL-2.0-or-later"
description = "Qualcomm GPU device for QEMU"
resolver = "2"
publish = false
keywords = []
categories = []
rust-version = "1.63.0"

[features]

default = ["gen8-2-1"]

# GPU Version
gen8-2-1 = []

[lib]
crate-type = ["staticlib"]

[dependencies]
bilge = { version = "0.2.0" }
bilge-impl = { version = "0.2.0" }
qemu_api = { path = "../../../qemu-api" }
qemu_api_macros = { path = "../../../qemu-api-macros" }

[lints]
workspace = true
