# Copyright (c) 2026 Qualcomm Innovation Center, Inc. All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0-or-later

name: Ubuntu Builds

on:
  push:
    branches:
      - 'libqemu/**'
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-libqemu:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        preset: [ debug, release, san ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo quic/install-deps.sh

      - name: Configure
        run: cmake --preset "${{ matrix.preset }}"

      - name: Build
        run: cmake --build --preset "${{ matrix.preset }}" --parallel $(nproc)

  build-qemu-hexagon:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo quic/install-deps.sh

      - name: Configure
        run: ./quic/build.sh configure hexagon

      - name: Build
        run: ./quic/build.sh build

      - name: Pack build tree
        if: matrix.os == 'ubuntu-24.04'
        run: tar czf build.tar.gz build

      - name: Upload build tree
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu-24.04-hexagon
          path: build.tar.gz
          retention-days: 1
          compression-level: 0

  build-qemu-aarch64:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo quic/install-deps.sh

      - name: Configure
        run: ./quic/build.sh configure aarch64

      - name: Build
        run: ./quic/build.sh build

  functional-tests:
    needs: build-qemu-hexagon
    uses: ./.github/workflows/functional-tests.yml
    with:
      runs-on: ubuntu-24.04
      artifact-name: build-ubuntu-24.04-hexagon
