system_ss.add(when: 'CONFIG_QCOM_CC', if_true: files('cc.c'))
system_ss.add(when: 'CONFIG_QCOM_CC', if_true: files('gpucc.c'))
system_ss.add(when: 'CONFIG_QCOM_CC', if_true: files('dispcc.c'))
system_ss.add(when: 'CONFIG_QCOM_CC', if_true: files('gcc.c'))
system_ss.add(when: 'CONFIG_QCOM_CC', if_true: files('clk-alpha-pll.c'))

